tagio/models/__init__.py
"""Mdoel modules.

mapping among objects and tables
"""

tagio/models/user.py
"""User module.

define object user and role.
"""

import datetime as dt

from flask_security import RoleMixin, UserMixin

from tagio.extensions import bcrypt
from tagio.database import (
    Column,
    db,
    Model,
    SurrogatePK,
)


roles_users = db.Table('roles_users',
                       Column('user_id', db.Integer(), db.ForeignKey('users.id')),
                       Column('role_id', db.Integer(), db.ForeignKey('roles.id')))


class Role(RoleMixin, SurrogatePK, Model):
    """A role for a user."""

    __tablename__ = 'roles'
    name = Column(db.String(80), unique=True, nullable=False)
    description = Column(db.String(255))

    def __init__(self, name, description='', **kwargs):
        """Create instance."""
        db.Model.__init__(self, name=name, description=description, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<Role({name})>'.format(name=self.name)


class User(UserMixin, SurrogatePK, Model):
    """A user of the app."""

    __tablename__ = 'users'
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(80), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.String(128), nullable=True)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)
    last_login_at = Column(db.DateTime)
    current_login_at = Column(db.DateTime)
    last_login_ip = Column(db.String(50))
    current_login_ip = Column(db.String(50))
    login_count = Column(db.Integer)

    roles = db.relationship('Role', secondary=roles_users,
                            backref=db.backref('users', lazy='dynamic'))

    def __init__(self, username, email, password=None, **kwargs):
        """Create instance."""
        db.Model.__init__(self, username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        """Set password."""
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        """Check password."""
        return bcrypt.check_password_hash(self.password, value)

    @property
    def full_name(self):
        """Full user name."""
        return '{0} {1}'.format(self.first_name, self.last_name)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<User({username!r})>'.format(username=self.username)

tagio/user/models.py
# -*- coding: utf-8 -*-
"""User models."""
import datetime as dt

from flask_login import UserMixin

from tagio.database import Column, Model, SurrogatePK, db, reference_col, relationship
from tagio.extensions import bcrypt


class Role(SurrogatePK, Model):
    """A role for a user."""

    __tablename__ = 'roles'
    name = Column(db.String(80), unique=True, nullable=False)
    user_id = reference_col('users', nullable=True)
    user = relationship('User', backref='roles')

    def __init__(self, name, **kwargs):
        """Create instance."""
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<Role({name})>'.format(name=self.name)


class User(UserMixin, SurrogatePK, Model):
    """A user of the app."""

    __tablename__ = 'users'
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(80), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.String(128), nullable=True)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)

    def __init__(self, username, email, password=None, **kwargs):
        """Create instance."""
        db.Model.__init__(self, username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        """Set password."""
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        """Check password."""
        return bcrypt.check_password_hash(self.password, value)

    @property
    def full_name(self):
        """Full user name."""
        return '{0} {1}'.format(self.first_name, self.last_name)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<User({username!r})>'.format(username=self.username)

tagio/forms.py
"""Form modules.

Define forms
"""

from flask_wtf import Form
from wtforms import PasswordField, TextField, HiddenField, BooleanField, SubmitField
from wtforms.validators import DataRequired

from tagio.models.user import User


class LoginForm(Form):
    """Login.

    login
    """

    next = HiddenField()
    username = TextField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember me', default=False)
    submit = SubmitField('Submit')

    def __init__(self, *args, **kwargs):
        """constructor."""
        super(LoginForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """validate user input."""
        initial_validation = super(LoginForm, self).validate()
        if not initial_validation:
            return False

        self.user = User.query.filter_by(username=self.username.data).first()
        if not self.user:
            self.username.errors.append('Invalid username or password!')
            return False

        if not self.user.check_password(self.password.data):
            self.username.errors.append('Invalid username or password!')
            return False

        if not self.user.active:
            self.username.errors.append('User not activated')
            return False
        return True

tagio/__init__.py
"""Main application package."""

tagio/app.py
# -*- coding: utf-8 -*-
"""The app module, containing the app factory function."""
from flask import Flask, render_template
from flask_security import SQLAlchemyUserDatastore

from tagio import views
from tagio.assets import assets
from tagio.extensions import bcrypt, cache, csrf_protect, db, debug_toolbar, login_manager, migrate, security
from tagio.settings import ProdConfig


def create_app(config_object=ProdConfig):
    """An application factory, as explained here: http://flask.pocoo.org/docs/patterns/appfactories/.

    :param config_object: The configuration object to use.
    """
    app = Flask(__name__)
    app.config.from_object(config_object)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app


def register_extensions(app):
    """Register Flask extensions."""
    assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    csrf_protect.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)

    from tagio.models.user import User, Role
    from tagio.forms import LoginForm
    security.init_app(app, SQLAlchemyUserDatastore(db, User, Role), login_form=LoginForm)

    return None


def register_blueprints(app):
    """Register Flask blueprints."""
    app.register_blueprint(views.public.blueprint)
    app.register_blueprint(views.user.blueprint)
    app.register_blueprint(views.api.blueprint)
    return None


def register_errorhandlers(app):
    """Register error handlers."""
    def render_error(error):
        """Render error template."""
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template('{0}.html'.format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None

tagio/utils/__init__.py
# -*- coding: utf-8 -*-
"""Helper utilities and decorators."""
from flask import flash


def flash_errors(form, category='warning'):
    """Flash all errors for a form."""
    for field, errors in form.errors.items():
        for error in errors:
            flash('{0} - {1}'.format(getattr(form, field).label.text, error), category)

tagio/views/__init__.py
"""View modules.

web logic
"""

from . import public, user, api

__all__ = ('public', 'user', 'api')

tagio/views/api.py
"""API.

api
"""
from flask import Blueprint, jsonify, request
from flask_security import auth_token_required

from tagio.models.user import User
from tagio.extensions import csrf_protect

blueprint = Blueprint('api',
                      __name__,
                      url_prefix='/api')


@blueprint.route('/v<string:version>/login', methods=['POST'])
@csrf_protect.exempt
def login(version):
    """Login.

    login to retrieve token.
    """
    if version == '1':
        return _login_first_version()

    return jsonify({'code': 1, 'msg': 'Invalid version'})


def _login_first_version():
    username = request.form.get('username')
    password = request.form.get('password')

    if username is None or password is None:
        return jsonify({'code': 2, 'msg': 'Invalid parameter'})

    username = username.strip().lower()

    user = User.query.filter(User.username == username).first()
    if user is None:
        return jsonify({'code': 2, 'msg': 'Invalid parameter'})

    flag = user.check_password(password)
    if not flag:
        return jsonify({'code': 2, 'msg': 'Invalid parameter'})

    return jsonify({'code': 0, 'token': user.get_auth_token()})


@blueprint.route('/v<string:version>/users', methods=['GET'])
@auth_token_required
def users(version):
    """Users.

    list all users.
    """
    if version == '1':
        users = User.query.all()
        return jsonify({'code': 0, 'msg': {user.id: {'name': user.username} for user in users}})

    return jsonify({'code': 1, 'msg': 'Invalid version'})

tagio/views/public.py
# -*- coding: utf-8 -*-
"""Public section, including homepage and signup."""
from flask import Blueprint, render_template

from tagio.models.user import User
from tagio.extensions import login_manager

blueprint = Blueprint('public', __name__, static_folder='../static')


@login_manager.user_loader
def load_user(user_id):
    """Load user by ID."""
    return User.get_by_id(int(user_id))


@blueprint.route('/', methods=['GET', 'POST'])
def home():
    """Home page."""
    return render_template('public/home.html')


@blueprint.route('/about/')
def about():
    """About page."""
    return render_template('public/about.html')

tagio/views/user.py
"""User.

user controller
"""

from flask_security import login_required
from flask import Blueprint, render_template


blueprint = Blueprint('user',
                      __name__,
                      url_prefix='/users',
                      static_folder='../static')


@blueprint.route('/')
@login_required
def members():
    """List members."""
    return render_template('users/members.html')

tagio/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

tagio/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© Maker Hanoi</li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('public.about') }}">About</a></li>

      <li><a href="mailto:makerhanoi@gmail.com">Contact</a></li>
    </ul>
  </small>
</footer>

tagio/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}
  
    A device management system
  
    {% endblock %}
  </title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  <link rel="stylesheet" href="{{ url_for('static', filename='libs/font-awesome4/css/font-awesome.min.css') }}">
  {% assets "css_all" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}

  {% block css %}{% endblock %}

</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
{% with form=form  %}
{% include "nav.html" %}
{% endwith %}

<header>{% block header %}{% endblock %}</header>
<div class="{% block content_class %}container{% endblock content_class %}">

  <div role="main">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{message}}
        </div><!-- end .alert -->
        {% endfor %}
      </div><!-- end col-md -->
    </div><!-- end row -->
        {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
  </div>

</div><!-- end container -->

{% include "footer.html" %}

<!-- JavaScript at the bottom for fast page loading -->
{% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}
</body>
</html>

tagio/templates/macros.html
{% macro render_checkbox(field) %}
<div class="checkbox{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id }}">
        {{ field }}{{ field.label.text }}
    </label>
    <span class="help-inline">{{ field.description }}</span>
    {% if field.errors -%}
    <ul class="help-block">
        {% for error in field.errors -%}
        <li>{{ error|e }}</li>
        {%- endfor %}
    </ul>
    {%- endif %}
</div>
{% endmacro%}

{% macro render_radio(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    {{ field.label(class_="control-label") }}
    <div class="">
        {% for subfield in field -%}
        <label for="{{ subfield.id }}" class="radio-inline">
            {{ subfield }} {{ subfield.label.text }}
        </label>
        {%- endfor %}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <li>{{ error }}</li>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}

{% macro render_datepicker(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label class="control-label"
        for="{{ field.id }}">
        {{ field.label }}
    </label>
    <div class="">
        {{ field() }}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <li>{{ error }}</li>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}

{% macro render_textarea(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label class="control-label"
        for="{{ field.id }}">
        {{ field.label }}
    </label>
    <div class="">
        {{ field(class_="form-control", rows="4") }}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <li>{{ error }}</li>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}

{% macro render_file(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label class="control-label"
        for="{{ field.id }}">
        {{ field.label }}
    </label>
    <div class="">
        {{ field }}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <li>{{ error }}</li>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}

{% macro render_input(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label class="control-label"
        for="{{ field.id }}">
        {{ field.label }}
    </label>
    <div class="">
        {{ field(class_="form-control") }}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <span class="help-block error">{{ error }}</span>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}

{% macro render_action(field) %}
<div class="form-group">
    <div class="form-actions">
        {{ field(class_="btn btn-primary") }}
    </div>
</div>
{% endmacro %}

{% macro render_form(url, form, horizontal=False, legend=None, confirm_msg=None, formid=None) %}
{% set idattr = "id=" + formid if formid else "" %}
<form {{idattr}} class="{% if horizontal %}form-horizontal{% endif %}" method="POST" action="{{ url }}"
    {% if confirm_msg %}onsubmit='return confirm("{{ confirm_msg }}");' {% endif %}
    {% if form.multipart %}enctype="multipart/form-data"{% endif %} >
    {{ form.hidden_tag() }}
        {% if legend %}
        <legend>{{ legend|safe }}</legend>
        {% endif %}
        {% set focus = True %}
        {% for field in form %}
            {% if field.type != "HiddenField" and field.type != "CSRFTokenField" %}
                {% if field.type == "RadioField" %}
                    {{ render_radio(field) }}
                {% elif field.type == "BooleanField" %}
                    {{ render_checkbox(field) }}
                {% elif field.type == "SubmitField" %}
                    {{ render_action(field) }}
                {% elif field.type == "TextAreaField" %}
                    {{ render_textarea(field) }}
                {% elif field.type == "DateField" %}
                    {{ render_datepicker(field) }}
                {% elif field.type == "FileField" %}
                    {{ render_file(field) }}
                {% elif field.type == "TextField" %}
                    {% if focus %}
                        {{ render_input(field) }}
                        {% set focus = False %}
                    {% else %}
                        {{ render_input(field) }}
                    {% endif %}
                {% else %}
                    {{ render_input(field) }}
                {% endif %}
            {% endif %}
        {% endfor %}
</form>
{% endmacro %}

{% macro render_pagination(pagination, endpoint) %}
  <ul class="pagination" style="margin-top:0px;">
  {%- for page in pagination.iter_pages() %}
    {% if page %}
      {% if page != pagination.page %}
       <li><a href="{{ url_for(endpoint, page=page, **kwargs) }}">{{ page }}</a></li>
      {% else %}
        <li class="active"><a href="#">{{ page }}</a></li>
      {% endif %}
    {% else %}
      <li><span class=ellipsis>…</span></li>
    {% endif %}
  {%- endfor %}
  </ul>
{% endmacro %}

tagio/templates/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{{ url_for('public.home') }}">

      A device management system

    </a>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><a href="{{ url_for('public.home') }}">Home</a></li>
      <li><a href="{{ url_for('public.about') }}">About</a></li>
    </ul>
    {% if current_user and current_user.is_authenticated %}
    <ul class="nav navbar-nav navbar-right">
        <li>
            <p class="navbar-text"><a class="navbar-link" href="{{ url_for('user.members') }}">Logged in as {{ current_user.username }}</a></p>
        </li>
        <li><a class="navbar-link" href="{{ url_for('security.logout') }}"><i class="fa fa-sign-out"></i></a></li>
    </ul>
    {% else %}
    <ul class="nav navbar-nav navbar-right">
      <li><a class="navbar-link" href="{{ url_for('security.login') }}"><i class="fa fa-sign-in"></i></a></li>
    </ul>
    {% endif %}
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>